""" add surname

Revision ID: 16cd4a9d4a1f
Revises: 0ddc960cfaf1
Create Date: 2025-12-04 17:24:38.582064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16cd4a9d4a1f'
down_revision = '0ddc960cfaf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(length=32), server_default='', nullable=False))
        batch_op.create_index(batch_op.f('ix_authors_surname'), ['surname'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authors_surname'))
        batch_op.drop_column('surname')

    # ### end Alembic commands ###
